name: pokedex_app
description: Pokedex application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # features
  feature_home:
    path: lib_feature_home

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
