name: pokedex_app
description: Pokedex application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Features
  feature_home:
    path: lib_feature_home
  feature_splash:
    path: lib_feature_splash
  feature_pokemon:
    path: lib_feature_pokemon
  feature_pokemons:
    path: lib_feature_pokemons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
