name: feature_pokemons
description: App splash feature
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets:
    path: ../lib_assets
  core:
    path: ../lib_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
