name: feature_home
description: App home feature
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../lib_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
